### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0x94 in position 14486: invalid start byte

### ISSUE THREAD

**Issue by pengqi** [studio-ousia/mprpc#12]
Is it possible to send binary data directly?
I have encoded the binary data with base64 before sending, but still got this exception sometimes: "UnicodeDecodeError: 'utf8' codec can't decode byte 0x94 in position 14486: invalid start byte".

**Comment by ikuyamada** [comment]
As base64 converts the binary data into plain text, you can safely send the data using mprpc.
