### ISSUE TITLE
Server is not threadsafe

### ISSUE THREAD

**Issue by hendrik-cliqz** [studio-ousia/mprpc#13]
Using mprpc on heavy load we experienced issues with corrupted data and finally found the issue:

The server is not threadsafe or 'greenlet safe':

Unpacker and Packer are member variables and therefore reused in all co-routines. That's not an issue for Packer due to the way it is used, but Unpacker buffers data. If a context-switch happens - for example because we wait for more data from the socket - the buffered data is read or written in a wrong context which causes data corruption. 

Every connection must have its own Packer/Unpacker instance.

Feel free to have a look at my fork (I require #11 in my app, so it diverges from origin).

(I guess in your app you only send small message, so this problem does not happen for you)

**Comment by ikuyamada** [comment]
@hendrik-cliqz Thank you very much for your valuable comment.
I agree that the unpacker can cause the problem if a context switch happens in the middle of *feeding* the data to it.
Therefore, unpacker *must* be in the local scope as you have fixed in your fork.

**Comment by ikuyamada** [comment]
I have just uploaded a new version of mprpc 0.1.5 with the fixes of this issue.
