### ISSUE TITLE
Asynchronous mode

### ISSUE THREAD

**Issue by Pastafarianist** [studio-ousia/mprpc#14]
Your competitor, `msgpack-rpc-python`, supports asynchronous calls [in the client](https://github.com/msgpack-rpc/msgpack-rpc-python/blob/master/example/bench_client.py#L21) and, judging by [this code](https://github.com/msgpack-rpc/msgpack-rpc-python/blob/master/msgpackrpc/server.py#L50), in the server. Are there plans to implement asynchronous mode in `mprpc`?

**Comment by ikuyamada** [comment]
Thank you for your comment.
As you may know, mprpc is based on gevent and greenlet.
With gevent and greenlet, you can avoid many cases where the *async* calls are needed by using coroutines.
On the other hand, msgpack-rpc-python is built on top of tornado which does not have such functionality so async calls are effective.
mprpc aims to provide a sheer layer on top of gevent to enable to use RPC easier.
So we do not currently have plans to implement async modes.

**Comment by Pastafarianist** [comment]
Thank you for answering.

**Comment by pykler** [comment]
@Pastafarianist see this thread if you are still stuck with this https://github.com/studio-ousia/mprpc/issues/28#issuecomment-234033684
