### ISSUE TITLE
Custom datatypes via default and ext_hook

### ISSUE THREAD

**Issue by Pastafarianist** [studio-ousia/mprpc#15]
Currently it is impossible to add transparent support for custom datatypes, although the official msgpack specification supports them (see [here](https://github.com/msgpack/msgpack-python/blob/master/README.rst#extended-types)). The only way to control serialization is through `(un)pack_encoding`. Are there plans to implement support for custom types?

**Comment by ikuyamada** [comment]
It would be nice to have the feature to customize the behavior of MessagePack such as custom datatypes. I am going to add two arguments: *pack_params* and *unpack_params* in the next version (please see the referenced commit). You can specify arbitrary arguments to MessagePack such as *default* or *object_hook*.

**Comment by Pastafarianist** [comment]
This is amazing. You are incredibly helpful. Thank you.
