### ISSUE TITLE
MPRPC stalls when too many clients connect to one server

### ISSUE THREAD

**Issue by pykler** [studio-ousia/mprpc#28]
I have 100 concurrent connection, but the server seems stalled.

**Comment by ikuyamada** [comment]
If you could, would you please provide code to reproduce this?
We use Mprpc for high-traffic production environments, but have not seen such an issue.

**Comment by pykler** [comment]
I wrote a small test, and it seems the most basic example in the docs is not asynchronous. Which is probably why I hit issues. How can you integrate gevent so that the server is asynchronous?

This server I am building is making a lot of io requests, so many parallel requests can / should be handled in parallel.

**Comment by ikuyamada** [comment]
What Is the basic example? Is it sum_server.py and sum_client.py?
If so, If I recall correctly, these code run asynchronously.

**Comment by pykler** [comment]
If you add a sleep before the calculation and put some print statements. Then start multiple clients, you will see that the requests to the server are sequential the server only responds to the next client when it finished with the first. So if you put `time.sleep(10)` each request will take 10 seconds after the previous request finishes. ie. not async.

**Comment by pykler** [comment]
So here are my changes to sum_server.py ... and follows is the output you can see that no two requests interleave. Requests are waiting till the previous one finishes

```
-> 1 % cat sum_server.py
# -*- coding: utf-8 -*-

from gevent.server import StreamServer

from mprpc import RPCServer

import time, datetime
import uuid

class SumServer(RPCServer):
    def sum(self, x, y):
        req_id = str(uuid.uuid1())
        print req_id, 'S', datetime.datetime.now()
        time.sleep(3)
        print req_id, 'E', datetime.datetime.now()
        return x + y



server = StreamServer(('127.0.0.1', 6000), SumServer())
server.serve_forever()
```

```
-> % python sum_server.py                                                                                     [34/305]
4445f7e6-4ea0-11e6-abce-542696d05c69 S 2016-07-20 14:34:52.866854
4445f7e6-4ea0-11e6-abce-542696d05c69 E 2016-07-20 14:34:55.869817
46132487-4ea0-11e6-9ecf-542696d05c69 S 2016-07-20 14:34:55.877284
46132487-4ea0-11e6-9ecf-542696d05c69 E 2016-07-20 14:34:58.882227
47ddb9de-4ea0-11e6-a1fe-542696d05c69 S 2016-07-20 14:34:58.882687
47ddb9de-4ea0-11e6-a1fe-542696d05c69 E 2016-07-20 14:35:01.886278
49a81bf8-4ea0-11e6-bd68-542696d05c69 S 2016-07-20 14:35:01.886808
49a81bf8-4ea0-11e6-bd68-542696d05c69 E 2016-07-20 14:35:04.886843
4b71f1d1-4ea0-11e6-8158-542696d05c69 S 2016-07-20 14:35:04.887209
4b71f1d1-4ea0-11e6-8158-542696d05c69 E 2016-07-20 14:35:07.887500
4d3bce0c-4ea0-11e6-889c-542696d05c69 S 2016-07-20 14:35:07.887845
4d3bce0c-4ea0-11e6-889c-542696d05c69 E 2016-07-20 14:35:10.888217
4f05ae30-4ea0-11e6-ab10-542696d05c69 S 2016-07-20 14:35:10.888576
4f05ae30-4ea0-11e6-ab10-542696d05c69 E 2016-07-20 14:35:13.893599
50d046f8-4ea0-11e6-8104-542696d05c69 S 2016-07-20 14:35:13.894032
50d046f8-4ea0-11e6-8104-542696d05c69 E 2016-07-20 14:35:16.897352
529aa1d7-4ea0-11e6-b48c-542696d05c69 S 2016-07-20 14:35:16.897948
529aa1d7-4ea0-11e6-b48c-542696d05c69 E 2016-07-20 14:35:19.897953
546476e1-4ea0-11e6-80bd-542696d05c69 S 2016-07-20 14:35:19.898360
546476e1-4ea0-11e6-80bd-542696d05c69 E 2016-07-20 14:35:22.903399
562f105c-4ea0-11e6-b1a6-542696d05c69 S 2016-07-20 14:35:22.903839
562f105c-4ea0-11e6-b1a6-542696d05c69 E 2016-07-20 14:35:25.908807
```

**Comment by pykler** [comment]
This is what I was missing

```
from gevent import monkey
monkey.patch_all()
```

It is just a case of not knowing how to use gevent properly. Perhaps can you add a note in the documentation that you need to write code that makes use of context switching and perhaps use gevent's monkey patching to help make the stdlibrary in python more co-operative.

**Comment by ikuyamada** [comment]
Glad to hear that your issue was fixed. Also, I will consider to add explanation about *monkey_patching* somewhere.
