### ISSUE TITLE
pip install failed on windows

### ISSUE THREAD

**Issue by gushenghua** [studio-ousia/mprpc#29]
Running setup.py bdist_wheel for mprpc ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools,
tokenize;__file__='c:\\users\\gsh\\appdata\\local\\temp\\pip-build-6t2mww\\mprpc
\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replac
e('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\gsh\appdata\local\t
emp\tmp0uinjnpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\mprpc
  copying mprpc\constants.py -> build\lib.win-amd64-2.7\mprpc
  copying mprpc\exceptions.py -> build\lib.win-amd64-2.7\mprpc
  copying mprpc\__init__.py -> build\lib.win-amd64-2.7\mprpc
  creating build\lib.win-amd64-2.7\tests
  copying tests\test_rpc.py -> build\lib.win-amd64-2.7\tests
  copying tests\__init__.py -> build\lib.win-amd64-2.7\tests
  running egg_info
  writing requirements to mprpc.egg-info\requires.txt
  writing mprpc.egg-info\PKG-INFO
  writing top-level names to mprpc.egg-info\top_level.txt
  writing dependency_links to mprpc.egg-info\dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'mprpc.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'mprpc.egg-info\SOURCES.txt'
  copying mprpc\client.c -> build\lib.win-amd64-2.7\mprpc
  copying mprpc\client.pyx -> build\lib.win-amd64-2.7\mprpc
  copying mprpc\server.c -> build\lib.win-amd64-2.7\mprpc
  copying mprpc\server.pyx -> build\lib.win-amd64-2.7\mprpc
  running build_ext
  building 'mprpc.client' extension
  error: [Error 2]

  ----------------------------------------
  Failed building wheel for mprpc
  Running setup.py clean for mprpc
  Running setup.py bdist_wheel for gsocketpool ... done
  Stored in directory: C:\Users\gsh\AppData\Local\pip\Cache\wheels\e3\78\1d\4abf
01c720ba6b10bc8523be3902a2dfe62f499d325d995837
  Running setup.py bdist_wheel for msgpack-python ... done
  Stored in directory: C:\Users\gsh\AppData\Local\pip\Cache\wheels\86\a2\a1\e119
00a18451d91d1ce1857f281df317cebcd99b130a2ba200
Successfully built gsocketpool msgpack-python
Failed to build mprpc
Installing collected packages: greenlet, gevent, gsocketpool, msgpack-python, mp
rpc
  Running setup.py install for mprpc ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools
, tokenize;__file__='c:\\users\\gsh\\appdata\\local\\temp\\pip-build-6t2mww\\mpr
pc\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().repl
ace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\gsh\appdata\loc
al\temp\pip-wqyhje-record\install-record.txt --single-version-externally-managed
 --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\mprpc
    copying mprpc\constants.py -> build\lib.win-amd64-2.7\mprpc
    copying mprpc\exceptions.py -> build\lib.win-amd64-2.7\mprpc
    copying mprpc\__init__.py -> build\lib.win-amd64-2.7\mprpc
    creating build\lib.win-amd64-2.7\tests
    copying tests\test_rpc.py -> build\lib.win-amd64-2.7\tests
    copying tests\__init__.py -> build\lib.win-amd64-2.7\tests
    running egg_info
    writing requirements to mprpc.egg-info\requires.txt
    writing mprpc.egg-info\PKG-INFO
    writing top-level names to mprpc.egg-info\top_level.txt
    writing dependency_links to mprpc.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'mprpc.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'mprpc.egg-info\SOURCES.txt'
    copying mprpc\client.c -> build\lib.win-amd64-2.7\mprpc
    copying mprpc\client.pyx -> build\lib.win-amd64-2.7\mprpc
    copying mprpc\server.c -> build\lib.win-amd64-2.7\mprpc
    copying mprpc\server.pyx -> build\lib.win-amd64-2.7\mprpc
    running build_ext
    building 'mprpc.client' extension
    error: [Error 2]

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\
\users\\gsh\\appdata\\local\\temp\\pip-build-6t2mww\\mprpc\\setup.py';exec(compi
le(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __fil
e__, 'exec'))" install --record c:\users\gsh\appdata\local\temp\pip-wqyhje-recor
d\install-record.txt --single-version-externally-managed --compile" failed with
error code 1 in c:\users\gsh\appdata\local\temp\pip-build-6t2mww\mprpc\

**Comment by ikuyamada** [comment]
I am sorry but I do not currently have Windows machine. Do you have any ideas that cause this setup error?
