### ISSUE TITLE
is there an obvious way to cache requests?

### ISSUE THREAD

**Issue by kootenpv** [studio-ousia/mprpc#35]
I'd like to cache requests, same input same output.

Preferably so that no serialisation has to be done again, something like `functools.lru_cache`

Would you have an idea how to add that?

**Comment by ikuyamada** [comment]
I think using lru_cache is a good idea for this case.

**Comment by kootenpv** [comment]
My main question is that I do not really understand where should I place it...

in your Sum example, how will I prevent that your package will have to reserialize?

**Comment by ikuyamada** [comment]
Now I understood your question. In the current implementation, it is impossible to add a caching function. In server.pyx, after receiving input data from a client, our system automatically deserializes the input data and calls the user function with the input data as arguments.
https://github.com/studio-ousia/mprpc/blob/master/mprpc/server.pyx#L71

**Comment by kootenpv** [comment]
Perhaps it is possible to add caching on the cython level then :)? I think it would be a very useful feature regarding speed.

For the record, I'm depending on you with https://github.com/kootenpv/spacy_api ^^

**Comment by ikuyamada** [comment]
Yes, caching feature can be implemented in the Cython code, but I want to maintain the simplicity and the speed of this library. BTW, I am also a user of SpaCy, your library looks interesting :)

**Comment by ikuyamada** [comment]
I know several similar libraries such as messagepack-rpc-python and zerorpc, but I don't know these libraries provide this kind of caching feature.
