### ISSUE TITLE
Reconnect if disconnected

### ISSUE THREAD

**Issue by rmdort** [studio-ousia/mprpc#40]
Hi, We are trying to use mprpc to serve machine learning models in production using a FLASK server. Sometimes we have to restart RPC server.

The first request after a restart gets the response `[Errno 61] Connection refused in StartServer.py:30`. Subsequent requests work.

I want to know if there is anyway to reconnect to the socket if its disconnected. This is how i am connected

````
=> FLASK server
def on_post():
    with client_pool.connection() as client:
       client.call('predict', query)
````

**Comment by ikuyamada** [comment]
mprpc automatically reconnects a socket when a socket error is occurred.
https://github.com/studio-ousia/mprpc/blob/master/mprpc/client.pyx#L248

Generally, disconnected sockets can only be found by reading or writing to the sockets. So I think the current implementation (if the socket is disconnected, it raises a socket error and reconnects the socket) is reasonable.

**Comment by rmdort** [comment]
ok noted. Do you think the following is the right implementation? 

````
def reconnect_to_socket ():
  global client_pool
  client_pool = gsocketpool.pool.Pool(RPCPoolClient, dict(host='127.0.0.1', port=6000))

try:
  with client_pool.connection() as client:
    if client.is_connected():
       # Call handler
    else:
       reconnect_to_socket()
except:
  reconnect_to_socket()
````

**Comment by ikuyamada** [comment]
yes, it looks good 👍
