### ISSUE TITLE
Sending blobs (byte arrays) results in encoding errors

### ISSUE THREAD

**Issue by mbr0wn** [studio-ousia/mprpc#43]
Similarly to #12, I would like to send blobs using mprpc (_not_ going through the Base64 encoding overhead, though). Both MessagePack spec and msgpack-python support this feature.

With mprpc, there seems to be no combination of pack/unpack encoding parameters that will let me send random binary data. Here's a modified version of the SumServer example, it'll just send me back what I sent:

```py
from gevent.server import StreamServer
from mprpc import RPCServer

class EchoServer(RPCServer):
    def __init__(self):
        RPCServer.__init__(self)

    def ping(self, x):
        #print(x)
        return x

server = StreamServer(('127.0.0.1', 6000), EchoServer())
server.serve_forever()
```

Here's a reliable way to crash it:
```py
from mprpc import RPCClient

client = RPCClient('127.0.0.1', 6000, )
print client.call('ping', b'\x0f\xf0')
```
...where as the binary string should simply stay a binary string, and go straight through. Here's my error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "mprpc/server.pyx", line 71, in mprpc.server.RPCServer.__call__ (mprpc/server.c:1591)
  File "mprpc/server.pyx", line 94, in mprpc.server.RPCServer._run (mprpc/server.c:1963)
  File "msgpack/_unpacker.pyx", line 469, in msgpack._unpacker.Unpacker.__next__ (msgpack/_unpacker.cpp:5459)
  File "msgpack/_unpacker.pyx", line 400, in msgpack._unpacker.Unpacker._unpack (msgpack/_unpacker.cpp:4483)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 1: unexpected end of data
Mon Oct 16 18:06:02 2017 <Greenlet at 0x7f1406673b90: _handle_and_close_when_done(<__main__.EchoServer object at 0x7f14061ce198>, <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with UnicodeDecodeError
```

msgpack-python, however, is perfectly happy serializing that:
```py
>>> import msgpack
>>> msgpack.unpackb(msgpack.packb(b'\x0f\xf0'))
b'\x0f\xf0'
```

I've also tried forcing types by specifying the pack/unpack encoding to utf-8, and also passing `use_bin_type=True` to the packers (on both sides), but then I simply get a different error message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "mprpc/server.pyx", line 71, in mprpc.server.RPCServer.__call__ (mprpc/server.c:1591)
  File "mprpc/server.pyx", line 105, in mprpc.server.RPCServer._run (mprpc/server.c:2149)
  File "mprpc/server.pyx", line 127, in mprpc.server.RPCServer._parse_request (mprpc/server.c:2572)
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
Mon Oct 16 18:11:28 2017 <Greenlet at 0x7ff792b94b90: _handle_and_close_when_done(<__main__.EchoServer object at 0x7ff7926ef198>, <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with TypeError
```

While the difference in error messages might be telling, those parameters are usually relevant for non-binary strings.

So, I think there's an issue with blobs and mprpc.

**Comment by mbr0wn** [comment]
Further experimentation did reveal a winning combo:

```py
from gevent.server import StreamServer
from mprpc import RPCServer

class EchoServer(RPCServer):
    def __init__(self):
        RPCServer.__init__(self,
            pack_encoding='utf-8',
            unpack_encoding='utf-8',
            pack_params={'use_bin_type': True},
                )

    def ping(self, x):
        # print(len(x))
        return x

server = StreamServer(('127.0.0.1', 6000), EchoServer())
server.serve_forever()
```

This will now work:
```py
from mprpc import RPCClient

b = b'\x0f\xf0'
client = RPCClient('127.0.0.1', 6000,
        pack_encoding='utf-8',
        unpack_encoding='utf-8',
        pack_params={'use_bin_type': True},
        )
print client.call('ping', b)
```

**Comment by mbr0wn** [comment]
OK, I found the issue. `mprpc` specifies defaults for the pack/unpack encoding, but not for the pack params. This puts msgpack-python into a bad state w.r.t. blobs, as specified here: https://github.com/msgpack/msgpack-python#string-and-binary-type

There's two ways of fixing mprpc into a consistent state: Either un-define default encodings (but that would be a non-backward-compatible change, and also, it wouldn't be very useful), or also specify pack parameters. Technically, the latter change is backward-incompatible, but only in the buggy case listed above.

**Comment by mbr0wn** [comment]
I can submit a pull request to fix this.

**Comment by ikuyamada** [comment]
Thank you for reporting the issue!
I think it is a good idea to specify *use_bin_type=True* as a default parameter of the packer.
Also, your pull request is very welcomed! 😄

**Comment by mbr0wn** [comment]
#44 fixes this. Note it didn't include cythonization. @ikuyamada you can close this issue whenever you feel like it as far as I'm concerned.

**Comment by ikuyamada** [comment]
So, let's close this issue now 😺

**Comment by fake-name** [comment]
I had run into this, but assumed it was the way it was for interoperability with other messagepack-rpc libraries. Cool!
