### ISSUE TITLE
When rpc return dictionary or complex structures, the direct return is much slower than returning encoded json string

### ISSUE THREAD

**Issue by zzeric** [studio-ousia/mprpc#53]
class WindServer(RPCServer):
    def test(self,a,b):
        return [list(range(100)),list(range(1000)),list(range(10000))]

    def test1(self,a,b):
        return json.dumps([list(range(100)),list(range(1000)),list(range(10000))])

t1 = time.time()
result = client.call("test",1,2)
t2 = time.time()
result = client.call("test1",1,2)
result = json.loads(result)
t3 = time.time()
print("direct way use %.3fs and json way use %.3fs" % (t2 - t1,t3-t2))

>>direct way use 0.104s and json way use 0.005s
the json version is 10x faster than direct return.

**Comment by ikuyamada** [comment]
Thank you for reporting the interesting issue!
However, the result cannot be reproduced on my laptop:

> direct way use 0.002s and json way use 0.006s

Please check your msgpack library is properly installed and run based on its Cython-based implementation (not pure-Python-based one).
Please refer to the documentation of the msgpack for details: https://github.com/msgpack/msgpack-python

**Comment by zzeric** [comment]
yes, after upgrading it is faster than json now
